// Code generated by goctl. DO NOT EDIT!
// Source: hello.proto

package server

import (
	"context"

	"github.com/ct-zh/goLearn/wheel/zrpc/simple2/internal/logic"
	"github.com/ct-zh/goLearn/wheel/zrpc/simple2/internal/svc"
	"github.com/ct-zh/goLearn/wheel/zrpc/simple2/types/pb"
)

type GreeterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGreeterServer
}

func NewGreeterServer(svcCtx *svc.ServiceContext) *GreeterServer {
	return &GreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *GreeterServer) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
